### ISSUE TITLE
测量有点儿小问题哦

### ISSUE THREAD

**Issue by lovely3x** [7heaven/GestureLock#2]
void onMeasure(){
if (lockers == null) {
            blockWidth = (length - (blockGap \* (depth - 1))) / depth;
            gestureWidth = blockWidth \* depth + blockGap \* (depth - 1);
...
}
这里存在多次测量的情况,所以第一次测量的结果未必准确.
放在if段中的话可能导致gestureWidth不准确,我测的情况是在480 \* 800 分辨率没问题.1080 \*  1920 上面出现了问题
这是布局文件
    <com.sevenheaven.GestureLock
        android:background="#558"
        android:id="@+id/gl_view_gesture_panel_gesture"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true" />

**Comment by 7heaven** [comment]
已经修改
